name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    uses: bndynet/gh.flows/.github/workflows/npm.yml@main
    with:
      node-version: '24'                             # default: '20'
      working-directory: '.'                         # default: '.'
      registry-url: 'https://registry.npmjs.org'     # default registry
      lint-command: ''                               # default: 'npm run lint'
      test-command: ''                               # default: 'npm test'
      build-command: 'npm run build'                 # default: 'npm run build'
      publish-enabled: true                          # default: false
      publish-auth-method: 'oidc'                    # default: token (or oidc)
      publish-tag: 'latest'                          # default: 'latest'
      publish-provenance: true                       # default: true
